[package]
name = "bevy_oxr"
version = "0.1.0"
edition = "2021"
description = "Community crate for OpenXR in Bevy"
repository = "https://github.com/awtterpip/bevy_openxr"
license = "MIT/Apache-2.0"


[features]
default = ["linked"]
linked = ["openxr/linked"]
webxr = []

[workspace]
members = ["examples/android", "examples/demo"]

[dependencies]
anyhow = "1.0.75"
ash = "0.37.3"
bevy = "0.12"
mint = "0.5.9"
wgpu = "0.17.1"
wgpu-core = { version = "0.17.1", features = ["vulkan"] }
wgpu-hal = "0.17.1"
wasm-bindgen = "0.2.78"
web-sys = "0.3.55"

[target.'cfg( target_family = "unix" )'.dependencies]
openxr = { version = "0.17.1", features = ["mint"] }

[target.'cfg(not(target_family = "unix"))'.dependencies]
openxr = { version = "0.17.1", features = ["mint", "static"] }

[dev-dependencies]
bevy = "0.12"
color-eyre = "0.6.2"
bevy_rapier3d = { git = "https://github.com/devil-ira/bevy_rapier", branch = "bevy-0.12" }

[[example]]
name = "xr"
path = "examples/xr.rs"

[profile.release]
debug = true
